
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2018.3.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*XILINX BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartns550.h"

/*
 * The configuration table for devices
 */

XUartNs550_Config XUartNs550_ConfigTable[] =
{
	{
		XPAR_UARTNS550_0_DEVICE_ID,
		XPAR_UARTNS550_0_BASEADDR,
		XPAR_UARTNS550_0_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_1_DEVICE_ID,
		XPAR_UARTNS550_1_BASEADDR,
		XPAR_UARTNS550_1_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_2_DEVICE_ID,
		XPAR_UARTNS550_2_BASEADDR,
		XPAR_UARTNS550_2_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_3_DEVICE_ID,
		XPAR_UARTNS550_3_BASEADDR,
		XPAR_UARTNS550_3_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_4_DEVICE_ID,
		XPAR_UARTNS550_4_BASEADDR,
		XPAR_UARTNS550_4_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_5_DEVICE_ID,
		XPAR_UARTNS550_5_BASEADDR,
		XPAR_UARTNS550_5_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_6_DEVICE_ID,
		XPAR_UARTNS550_6_BASEADDR,
		XPAR_UARTNS550_6_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_7_DEVICE_ID,
		XPAR_UARTNS550_7_BASEADDR,
		XPAR_UARTNS550_7_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_8_DEVICE_ID,
		XPAR_UARTNS550_8_BASEADDR,
		XPAR_UARTNS550_8_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_9_DEVICE_ID,
		XPAR_UARTNS550_9_BASEADDR,
		XPAR_UARTNS550_9_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_10_DEVICE_ID,
		XPAR_UARTNS550_10_BASEADDR,
		XPAR_UARTNS550_10_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_11_DEVICE_ID,
		XPAR_UARTNS550_11_BASEADDR,
		XPAR_UARTNS550_11_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_12_DEVICE_ID,
		XPAR_UARTNS550_12_BASEADDR,
		XPAR_UARTNS550_12_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_13_DEVICE_ID,
		XPAR_UARTNS550_13_BASEADDR,
		XPAR_UARTNS550_13_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_14_DEVICE_ID,
		XPAR_UARTNS550_14_BASEADDR,
		XPAR_UARTNS550_14_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_15_DEVICE_ID,
		XPAR_UARTNS550_15_BASEADDR,
		XPAR_UARTNS550_15_CLOCK_FREQ_HZ
	}
};


